apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apple.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "apple.name" . }}
    helm.sh/chart: {{ include "apple.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "apple.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "apple.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8500
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8500
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8500
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
